name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting. Today is $DAY_OF_WEEK!"
      - name: "Say Hello Mona it's Wednesday"
        run: echo "Today is $DAY_OF_WEEK!"
        env:
          DAY_OF_WEEK: Wednesday
