name: Master Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - 'development'
      - 'preset/*'
      - 'technical'
      - 'rc/[0-9]+.[0-9]+.[0-9]+'
      - 'rc/[0-9]+.[0-9]+.[0-9]+.[1-9]+'
concurrency:
  group: ${{vars.GITHUB_WORKFLOW}}-${{vars.GITHUB_REF_NAME}}
#  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  run-prebuild-tests:
    runs-on: ubuntu-latest
    name: Runs all pre-build tests
    steps:

      - name: Checkout REPOSITORY_NAME
        uses: actions/checkout@v3

      - name: echo ref_name
        run: | 
          echo ${GITHUB_WORKFLOW}-${GITHUB_REF_NAME}
          echo ${{ github.workflow }}-${{ github.ref_name }}
          sleep 70
          echo ${GITHUB_REF}
